# @package _global_
ENV_ID: asteroids
SEQUENCE: rew4
TASK_MODS:
  - []
  - ["life_loss_penalty"]
  - ["small_asteroid_only"]
  - ["large_asteroid_only"]
  - ["survival_reward"]

# --- More Options ---
# every_k_kills
# wave_clear_bonus
# flatten_asteroid_values 
