# @package _global_
ENV_ID: freeway
SEQUENCE: dyn4
TASK_MODS:
  - []
  - ["change_car_speed"]
  - ["faster_player"]
  - ["change_car_spawning"]
  - ["invert_cars"]

# --- More Options ---
# slower_player
# stop_all_cars
# static_cars
# slow_cars
