# @package _global_
ENV_ID: freeway
SEQUENCE: vis4
TASK_MODS:
  - []
  - ["change_player_color"]
  - ["change_car_color"]
  - ["grayscale_theme"]
  - ["bikes"]

# --- More Options ---
# change_road_color   
# black_cars
# frog
# new_lane_colors
# change_score_color