# @package _global_
ENV_ID: kangaroo
SEQUENCE: vis4
TASK_MODS:
  - []
  - ["chickens"]    
  - ["change_monkey_color"]      
  - ["change_background_color"]  
  - ["grayscale_theme"]      
  

# --- More Options ---
# change_score_color    
# change_kangaroo_color 
# ropes / chains       # ladder sprite swaps
# tanks / dragons / polarbears / snakes   # enemy reskins
# collectable_coins / collectable_diamonds           # fruit reskins
# replace_bell_with_flame / replace_bell_with_cactus
