# @package _global_
ENV_ID: seaquest
SEQUENCE: rew4
TASK_MODS:
  - []
  - ["life_loss_penalty"]     
  - ["diver_scoring_only"]   
  - ["penalize_diver_shoot"]   
  - ["survival_reward"] 

# --- More Options ---
# surface_load_bonus
# flatten_enemy_values