# @package _global_
ENV_ID: seaquest
SEQUENCE: dyn4
TASK_MODS:
  - []
  - ["faster_enemies"]
  - ["disable_enemies"]
  - ["faster_sub"]  
  - ["unlimited_oxygen"]


# --- More Options ---
# slower_enemies
# slower_sub 
# randomize_spawn
# diver_spawn_rate                          
# disable_enemies                           
# faster_oxygen_drain
# dense_spawn
# gravity