# @package _global_
ENV_ID: kangaroo
SEQUENCE: dyn4
TASK_MODS:
  - []
  - ["coconut_speed_x2"]   
  - ["no_monkey"]   
  - ["jump_gravity"]
  - ["change_kangaroo_speed"]

# --- More Options ---
# no_punch/crouch/jump
# change_monkey_speed
# randomize_coconuts
# no_monkey 
# no_falling_coconut