# @package _global_
ENV_ID: breakout
SEQUENCE: dyn4
TASK_MODS:
  - []
  - ["faster_paddle"] 
  - ["ball_drift"]
  - ["random_serve"] 
  - ["faster_ball"] 

# --- More Options ---
# slower_ball
# slower_paddle