# @package _global_
ENV_ID: freeway
SEQUENCE: vis4
TASK_MODS:
  - []
  - ["change_player_color"]
  - ["bikes"]
  - ["change_car_color"]
  - ["change_road_color"]

# --- More Options ---   
# grayscale_theme
# black_cars
# frog
# new_lane_colors
# change_score_color