# @package _global_
ENV_ID: seaquest
SEQUENCE: vis4
TASK_MODS:
  - []
  - ["change_water_color"]  
  - ["mines"]   
  - ["random_color_enemies"]   
  - ["change_sub_color"]    

# --- More Options ---
# grayscale_theme        
# change_enemy_color
# change_score_color